2023-06-29 08:14:31.749  INFO 13304 --- [ool-1-worker-87] c.a.k.c.s.p.ServiceMessagePublisher      : logLevel:Info,caller:com.amazonaws.kendra.connector.googledrive.services.GoogleDriveService.getAttachment()[Line:964],awsAccountId:871842996425,indexId:031cba04-ddc1-4077-bd73-5770e65efbd0,sourceId:1d63b6af-eb0e-4f7c-8fd2-ddd12b163b86,executionId:69899685-b89f-4a35-9aeb-01f0639e7690,message:Fetching content for file Copy of empty_txt_file.txt with file id 1VwozysxMpxIsk-Jkt3bp_0x1mQ2qVb_S and mime type text/plain for user test_user2@aws-kendra.com.
2023-06-29 08:14:31.751  INFO 13304 --- [ool-1-worker-87] c.a.k.c.g.helper.GoogleDriveHelper       : Fetching content for file name Copy of empty_txt_file.txt with file id 1VwozysxMpxIsk-Jkt3bp_0x1mQ2qVb_S and mime type text/plain
2023-06-29 08:14:31.751  INFO 13304 --- [ool-1-worker-87] c.a.k.c.g.helper.GoogleDriveHelper       : Processing large Non-Google Workspace document name Copy of empty_txt_file.txt with Id 1VwozysxMpxIsk-Jkt3bp_0x1mQ2qVb_S.
2023-06-29 08:14:31.753  INFO 13304 --- [ool-1-worker-87] c.a.k.c.g.helper.GoogleDriveHelper       : Fetching file Copy of empty_txt_file.txt content for file id 1VwozysxMpxIsk-Jkt3bp_0x1mQ2qVb_S from path C:\Users\ADMINI~1\AppData\Local\Temp\2\3cb2708e-f6ec-41d5-a0e6-e86f5425857c.
2023-06-29 08:14:32.029 ERROR 13304 --- [ool-1-worker-87] c.a.k.c.g.helper.GoogleDriveHelper       : Fetching file Copy of empty_txt_file.txt content for file id 1VwozysxMpxIsk-Jkt3bp_0x1mQ2qVb_S from path C:\Users\ADMINI~1\AppData\Local\Temp\2\3cb2708e-f6ec-41d5-a0e6-e86f5425857c.

com.google.api.client.http.HttpResponseException: 416 Requested range not satisfiable
GET https://www.googleapis.com/drive/v3/files/1VwozysxMpxIsk-Jkt3bp_0x1mQ2qVb_S?alt=media
{
  "error": {
    "code": 416,
    "message": "Request range not satisfiable",
    "errors": [{
      "message": "Request range not satisfiable",
      "domain": "global",
      "reason": "requestedRangeNotSatisfiable"
    }]
  }
}
        at com.google.api.client.http.HttpResponseException$Builder.build(HttpResponseException.java:293) ~[google-http-client-1.42.1.jar!/:1.42.1]
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1118) ~[google-http-client-1.42.1.jar!/:1.42.1]
        at com.google.api.client.googleapis.media.MediaHttpDownloader.executeCurrentRequest(MediaHttpDownloader.java:241) ~[google-api-client-2.0.0.jar!/:2.0.0]
        at com.google.api.client.googleapis.media.MediaHttpDownloader.download(MediaHttpDownloader.java:183) ~[google-api-client-2.0.0.jar!/:2.0.0]
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeMediaAndDownloadTo(AbstractGoogleClientRequest.java:653) ~[google-api-client-2.0.0.jar!/:2.0.0]
        at com.google.api.services.drive.Drive$Files$Get.executeMediaAndDownloadTo(Drive.java:5081) ~[google-api-services-drive-v3-rev20220815-2.0.0.jar!/:na]
        at com.amazonaws.kendra.connector.googledrive.helper.GoogleDriveHelper.getFileContentForNonGoogle(GoogleDriveHelper.java:901) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.helper.GoogleDriveHelper.getFileContent(GoogleDriveHelper.java:848) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.services.GoogleDriveService.lambda$getAttachment$29(GoogleDriveService.java:968) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.utils.CommonUtil.executeServiceCallsWithRetry(CommonUtil.java:51) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.services.GoogleDriveService.getAttachment(GoogleDriveService.java:967) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.client.GoogleDriveClient.buildFileItem(GoogleDriveClient.java:222) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.client.GoogleDriveClient.getItem(GoogleDriveClient.java:146) ~[classes!/:na]
        at com.amazonaws.kendra.connector.sdk.utils.MetricUtils.lambda$invoke$0(MetricUtils.java:97) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at com.amazonaws.kendra.connector.sdk.utils.MetricUtils.invoke(MetricUtils.java:66) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at com.amazonaws.kendra.connector.sdk.utils.MetricUtils.invoke(MetricUtils.java:96) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at com.amazonaws.kendra.connector.sdk.core.client.SdkRepositoryClient.getItem(SdkRepositoryClient.java:97) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at com.amazonaws.kendra.connector.sdk.core.indexer.RepositoryItemFetcher.retrieveItemFromRepository(RepositoryItemFetcher.java:95) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at com.amazonaws.kendra.connector.sdk.core.indexer.RepositoryItemFetcher.lambda$fetch$0(RepositoryItemFetcher.java:80) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at com.amazonaws.kendra.connector.sdk.utils.ParallelExecutor.lambda$executeFunctions$0(ParallelExecutor.java:69) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]

2023-06-29 08:14:32.035  INFO 13304 --- [ool-1-worker-87] c.a.k.c.g.helper.GoogleDriveHelper       : Couldn't delete created temp local file! :: C:\Users\ADMINI~1\AppData\Local\Temp\2\3cb2708e-f6ec-41d5-a0e6-e86f5425857coriginal file name::Copy of empty_txt_file.txt
2023-06-29 08:14:32.043 ERROR 13304 --- [ool-1-worker-87] c.a.k.c.g.helper.GoogleDriveHelper       : Exception occurred while fetching document Copy of empty_txt_file.txt with file id 1VwozysxMpxIsk-Jkt3bp_0x1mQ2qVb_S for user test_user2@aws-kendra.com.
2023-06-29 08:14:32.045 ERROR 13304 --- [ool-1-worker-87] c.a.k.c.googledrive.utils.CommonUtil     : GoogleDriveConnectorException occurred while retrying

com.amazonaws.kendra.connector.googledrive.exception.GoogleDriveConnectorException: Exception occurred while fetching content for file || Exception occurred while fetching content for file || 416 Requested range not satisfiable
GET https://www.googleapis.com/drive/v3/files/1VwozysxMpxIsk-Jkt3bp_0x1mQ2qVb_S?alt=media
{
  "error": {
    "code": 416,
    "message": "Request range not satisfiable",
    "errors": [{
      "message": "Request range not satisfiable",
      "domain": "global",
      "reason": "requestedRangeNotSatisfiable"
    }]
  }
}
        at com.amazonaws.kendra.connector.googledrive.helper.GoogleDriveHelper.getFileContent(GoogleDriveHelper.java:879) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.services.GoogleDriveService.lambda$getAttachment$29(GoogleDriveService.java:968) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.utils.CommonUtil.executeServiceCallsWithRetry(CommonUtil.java:51) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.services.GoogleDriveService.getAttachment(GoogleDriveService.java:967) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.client.GoogleDriveClient.buildFileItem(GoogleDriveClient.java:222) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.client.GoogleDriveClient.getItem(GoogleDriveClient.java:146) ~[classes!/:na]
        at com.amazonaws.kendra.connector.sdk.utils.MetricUtils.lambda$invoke$0(MetricUtils.java:97) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at com.amazonaws.kendra.connector.sdk.utils.MetricUtils.invoke(MetricUtils.java:66) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at com.amazonaws.kendra.connector.sdk.utils.MetricUtils.invoke(MetricUtils.java:96) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at com.amazonaws.kendra.connector.sdk.core.client.SdkRepositoryClient.getItem(SdkRepositoryClient.java:97) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at com.amazonaws.kendra.connector.sdk.core.indexer.RepositoryItemFetcher.retrieveItemFromRepository(RepositoryItemFetcher.java:95) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at com.amazonaws.kendra.connector.sdk.core.indexer.RepositoryItemFetcher.lambda$fetch$0(RepositoryItemFetcher.java:80) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at com.amazonaws.kendra.connector.sdk.utils.ParallelExecutor.lambda$executeFunctions$0(ParallelExecutor.java:69) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]
Caused by: com.amazonaws.kendra.connector.sdk.exception.ContinuableInternalServerError: Exception occurred while fetching content for file || 416 Requested range not satisfiable
GET https://www.googleapis.com/drive/v3/files/1VwozysxMpxIsk-Jkt3bp_0x1mQ2qVb_S?alt=media
{
  "error": {
    "code": 416,
    "message": "Request range not satisfiable",
    "errors": [{
      "message": "Request range not satisfiable",
      "domain": "global",
      "reason": "requestedRangeNotSatisfiable"
    }]
  }
}
        at com.amazonaws.kendra.connector.googledrive.helper.GoogleDriveHelper.getFileContentForNonGoogle(GoogleDriveHelper.java:905) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.helper.GoogleDriveHelper.getFileContent(GoogleDriveHelper.java:848) ~[classes!/:na]
        ... 19 common frames omitted

2023-06-29 08:14:32.049 ERROR 13304 --- [ool-1-worker-87] c.a.k.c.googledrive.utils.CommonUtil     : Skipping retry

com.amazonaws.kendra.connector.googledrive.exception.GoogleDriveConnectorException: Exception occurred while fetching content for file || Exception occurred while fetching content for file || 416 Requested range not satisfiable
GET https://www.googleapis.com/drive/v3/files/1VwozysxMpxIsk-Jkt3bp_0x1mQ2qVb_S?alt=media
{
  "error": {
    "code": 416,
    "message": "Request range not satisfiable",
    "errors": [{
      "message": "Request range not satisfiable",
      "domain": "global",
      "reason": "requestedRangeNotSatisfiable"
    }]
  }
}
        at com.amazonaws.kendra.connector.googledrive.helper.GoogleDriveHelper.getFileContent(GoogleDriveHelper.java:879) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.services.GoogleDriveService.lambda$getAttachment$29(GoogleDriveService.java:968) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.utils.CommonUtil.executeServiceCallsWithRetry(CommonUtil.java:51) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.services.GoogleDriveService.getAttachment(GoogleDriveService.java:967) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.client.GoogleDriveClient.buildFileItem(GoogleDriveClient.java:222) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.client.GoogleDriveClient.getItem(GoogleDriveClient.java:146) ~[classes!/:na]
        at com.amazonaws.kendra.connector.sdk.utils.MetricUtils.lambda$invoke$0(MetricUtils.java:97) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at com.amazonaws.kendra.connector.sdk.utils.MetricUtils.invoke(MetricUtils.java:66) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at com.amazonaws.kendra.connector.sdk.utils.MetricUtils.invoke(MetricUtils.java:96) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at com.amazonaws.kendra.connector.sdk.core.client.SdkRepositoryClient.getItem(SdkRepositoryClient.java:97) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at com.amazonaws.kendra.connector.sdk.core.indexer.RepositoryItemFetcher.retrieveItemFromRepository(RepositoryItemFetcher.java:95) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at com.amazonaws.kendra.connector.sdk.core.indexer.RepositoryItemFetcher.lambda$fetch$0(RepositoryItemFetcher.java:80) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at com.amazonaws.kendra.connector.sdk.utils.ParallelExecutor.lambda$executeFunctions$0(ParallelExecutor.java:69) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]
Caused by: com.amazonaws.kendra.connector.sdk.exception.ContinuableInternalServerError: Exception occurred while fetching content for file || 416 Requested range not satisfiable
GET https://www.googleapis.com/drive/v3/files/1VwozysxMpxIsk-Jkt3bp_0x1mQ2qVb_S?alt=media
{
  "error": {
    "code": 416,
    "message": "Request range not satisfiable",
    "errors": [{
      "message": "Request range not satisfiable",
      "domain": "global",
      "reason": "requestedRangeNotSatisfiable"
    }]
  }
}
        at com.amazonaws.kendra.connector.googledrive.helper.GoogleDriveHelper.getFileContentForNonGoogle(GoogleDriveHelper.java:905) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.helper.GoogleDriveHelper.getFileContent(GoogleDriveHelper.java:848) ~[classes!/:na]
        ... 19 common frames omitted

2023-06-29 08:14:32.053 ERROR 13304 --- [ool-1-worker-87] c.a.k.c.s.p.ServiceMessagePublisher      : logLevel:Error,caller:com.amazonaws.kendra.connector.googledrive.services.GoogleDriveService.getAttachment()[Line:979],awsAccountId:871842996425,indexId:031cba04-ddc1-4077-bd73-5770e65efbd0,sourceId:1d63b6af-eb0e-4f7c-8fd2-ddd12b163b86,executionId:69899685-b89f-4a35-9aeb-01f0639e7690,message:Exception occurred while Fetching content for file Copy of empty_txt_file.txt with file id 1VwozysxMpxIsk-Jkt3bp_0x1mQ2qVb_S for user test_user2@aws-kendra.com.
2023-06-29 08:14:32.064 ERROR 13304 --- [ool-1-worker-87] c.a.k.c.s.p.ServiceMessagePublisher      : logLevel:Error,caller:com.amazonaws.kendra.connector.googledrive.client.GoogleDriveClient.getItem()[Line:169],awsAccountId:871842996425,indexId:031cba04-ddc1-4077-bd73-5770e65efbd0,sourceId:1d63b6af-eb0e-4f7c-8fd2-ddd12b163b86,executionId:69899685-b89f-4a35-9aeb-01f0639e7690,message:1VwozysxMpxIsk-Jkt3bp_0x1mQ2qVb_S Skipping the document from ingestion as encountered failure in fetching content/ metadata of document :
2023-06-29 08:14:32.066  INFO 13304 --- [ool-1-worker-87] c.a.k.c.s.p.ServiceMessagePublisher      : logLevel:Info,caller:com.amazonaws.kendra.connector.sdk.core.indexer.RepositoryItemFetcher.retrieveItemFromRepository()[Line:101],awsAccountId:871842996425,indexId:031cba04-ddc1-4077-bd73-5770e65efbd0,sourceId:1d63b6af-eb0e-4f7c-8fd2-ddd12b163b86,executionId:69899685-b89f-4a35-9aeb-01f0639e7690,documentId:f2313af730d78b785ac2aa78d7c8a10636c5e5508b301a4d3845a4d571db20778fa5bf64572e0e5d86b470071601845f78fc385b1cc772ad175b2e3874648c0f,message:Error fetching item id from repository
2023-06-29 08:14:32.067 ERROR 13304 --- [ool-1-worker-87] .CustomerFailedDocumentMessagesPublisher : Got following exception when syncing documentId: f2313af730d78b785ac2aa78d7c8a10636c5e5508b301a4d3845a4d571db20778fa5bf64572e0e5d86b470071601845f78fc385b1cc772ad175b2e3874648c0f

com.amazonaws.kendra.connector.sdk.exception.ContinuableInternalServerError: Item not ingested : 1VwozysxMpxIsk-Jkt3bp_0x1mQ2qVb_S due to exception : Exception occurred while fetching file content
        at com.amazonaws.kendra.connector.googledrive.client.GoogleDriveClient.getItem(GoogleDriveClient.java:173) ~[classes!/:na]
        at com.amazonaws.kendra.connector.sdk.utils.MetricUtils.lambda$invoke$0(MetricUtils.java:97) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at com.amazonaws.kendra.connector.sdk.utils.MetricUtils.invoke(MetricUtils.java:66) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at com.amazonaws.kendra.connector.sdk.utils.MetricUtils.invoke(MetricUtils.java:96) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at com.amazonaws.kendra.connector.sdk.core.client.SdkRepositoryClient.getItem(SdkRepositoryClient.java:97) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at com.amazonaws.kendra.connector.sdk.core.indexer.RepositoryItemFetcher.retrieveItemFromRepository(RepositoryItemFetcher.java:95) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at com.amazonaws.kendra.connector.sdk.core.indexer.RepositoryItemFetcher.lambda$fetch$0(RepositoryItemFetcher.java:80) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at com.amazonaws.kendra.connector.sdk.utils.ParallelExecutor.lambda$executeFunctions$0(ParallelExecutor.java:69) ~[core-sdk-1.12-SNAPSHOT-jar-with-dependencies.jar!/:na]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]
Caused by: com.amazonaws.kendra.connector.sdk.exception.ContinuableInternalServerError: Exception occurred while fetching file content
        at com.amazonaws.kendra.connector.googledrive.utils.ExceptionHandler.handleException(ExceptionHandler.java:19) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.services.GoogleDriveService.getAttachment(GoogleDriveService.java:981) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.client.GoogleDriveClient.buildFileItem(GoogleDriveClient.java:222) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.client.GoogleDriveClient.getItem(GoogleDriveClient.java:146) ~[classes!/:na]
        ... 14 common frames omitted
Caused by: com.amazonaws.kendra.connector.googledrive.exception.GoogleDriveConnectorException: Exception occurred while fetching content for file || Exception occurred while fetching content for file || 416 Requested range not satisfiable
GET https://www.googleapis.com/drive/v3/files/1VwozysxMpxIsk-Jkt3bp_0x1mQ2qVb_S?alt=media
{
  "error": {
    "code": 416,
    "message": "Request range not satisfiable",
    "errors": [{
      "message": "Request range not satisfiable",
      "domain": "global",
      "reason": "requestedRangeNotSatisfiable"
    }]
  }
}
        at com.amazonaws.kendra.connector.googledrive.helper.GoogleDriveHelper.getFileContent(GoogleDriveHelper.java:879) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.services.GoogleDriveService.lambda$getAttachment$29(GoogleDriveService.java:968) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.utils.CommonUtil.executeServiceCallsWithRetry(CommonUtil.java:51) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.services.GoogleDriveService.getAttachment(GoogleDriveService.java:967) ~[classes!/:na]
        ... 16 common frames omitted
Caused by: com.amazonaws.kendra.connector.sdk.exception.ContinuableInternalServerError: Exception occurred while fetching content for file || 416 Requested range not satisfiable
GET https://www.googleapis.com/drive/v3/files/1VwozysxMpxIsk-Jkt3bp_0x1mQ2qVb_S?alt=media
{
  "error": {
    "code": 416,
    "message": "Request range not satisfiable",
    "errors": [{
      "message": "Request range not satisfiable",
      "domain": "global",
      "reason": "requestedRangeNotSatisfiable"
    }]
  }
}
        at com.amazonaws.kendra.connector.googledrive.helper.GoogleDriveHelper.getFileContentForNonGoogle(GoogleDriveHelper.java:905) ~[classes!/:na]
        at com.amazonaws.kendra.connector.googledrive.helper.GoogleDriveHelper.getFileContent(GoogleDriveHelper.java:848) ~[classes!/:na]
        ... 19 common frames omitted

2023-06-29 08:14:32.073 ERROR 13304 --- [ool-1-worker-87] .CustomerFailedDocumentMessagesPublisher : logLevel:Error,caller:com.amazonaws.kendra.connector.sdk.publisher.CustomerFailedDocumentMessagesPublisher.publish()[Line:128],indexId:031cba04-ddc1-4077-bd73-5770e65efbd0,dataSourceId:1d63b6af-eb0e-4f7c-8fd2-ddd12b163b86,dataSourceSyncExecutionId:69899685-b89f-4a35-9aeb-01f0639e7690,documentId:f2313af730d78b785ac2aa78d7c8a10636c5e5508b301a4d3845a4d571db20778fa5bf64572e0e5d86b470071601845f78fc385b1cc772ad175b2e3874648c0f,errorCode:InternalError,errorMessage:Internal error encountered during document sync, contact customer support
2023-06-29 08:14:32.089  INFO 13304 --- [ol-1-worker-115] c.a.k.c.s.p.ServiceMessagePublisher      : logLevel:Info,caller:com.amazonaws.kendra.connector.googledrive.client.GoogleDriveFullCrawlIterator.hasNext()[Line:93],awsAccountId:871842996425,indexId:031cba04-ddc1-4077-bd73-5770e65efbd0,sourceId:1d63b6af-eb0e-4f7c-8fd2-ddd12b163b86,executionId:69899685-b89f-4a35-9aeb-01f0639e7690,message:Checking for next document available in crawling queue.
2023-06-29 08:14:32.094  INFO 13304 --- [ol-1-worker-115] c.a.k.c.s.p.ServiceMessagePublisher      : logLevel:Info,caller:com.amazonaws.kendra.connector.googledrive.client.GoogleDriveFullCrawlIterator.hasNext()[Line:116],awsAccountId:871842996425,indexId:031cba04-ddc1-4077-bd73-5770e65efbd0,sourceId:1d63b6af-eb0e-4f7c-8fd2-ddd12b163b86,executionId:69899685-b89f-4a35-9aeb-01f0639e7690,message:Crawler not found to be running while waiting for crawling queue to be filled up.
2023-06-29 08:14:32.095  INFO 13304 --- [ol-1-worker-115] c.a.k.c.s.p.ServiceMessagePublisher      : logLevel:Info,caller:com.amazonaws.kendra.connector.googledrive.client.GoogleDriveFullCrawlIterator.hasNext()[Line:124],awsAccountId:871842996425,indexId:031cba04-ddc1-4077-bd73-5770e65efbd0,sourceId:1d63b6af-eb0e-4f7c-8fd2-ddd12b163b86,executionId:69899685-b89f-4a35-9aeb-01f0639e7690,message:Current crawling queue size is 0 and empty check status is true
2023-06-29 08:14:32.096  INFO 13304 --- [ol-1-worker-115] c.a.k.c.s.p.ServiceMessagePublisher      : logLevel:Info,caller:com.amazonaws.kendra.connector.sdk.core.crawler.Crawler.lambda$crawl$0()[Line:117],awsAccountId:871842996425,indexId:031cba04-ddc1-4077-bd73-5770e65efbd0,sourceId:1d63b6af-eb0e-4f7c-8fd2-ddd12b163b86,executionId:69899685-b89f-4a35-9aeb-01f0639e7690,message:Deleting stale documents.
2023-06-29 08:14:32.140  INFO 13304 --- [ol-1-worker-115] c.a.k.c.s.p.ServiceMessagePublisher      : logLevel:Info,caller:com.amazonaws.kendra.connector.sdk.core.crawler.Crawler.start()[Line:83],awsAccountId:871842996425,indexId:031cba04-ddc1-4077-bd73-5770e65efbd0,sourceId:1d63b6af-eb0e-4f7c-8fd2-ddd12b163b86,executionId:69899685-b89f-4a35-9aeb-01f0639e7690,message:The connector has successfully completed syncing documents.
2023-06-29 08:14:44.150  INFO 13304 --- [ol-1-worker-115] c.a.k.c.s.p.ServiceMessagePublisher      : logLevel:Info,caller:com.amazonaws.kendra.connector.sdk.manager.ConnectorMetricsManager.pollMetricQueueTillItsEmpty()[Line:191],awsAccountId:871842996425,indexId:031cba04-ddc1-4077-bd73-5770e65efbd0,sourceId:1d63b6af-eb0e-4f7c-8fd2-ddd12b163b86,executionId:69899685-b89f-4a35-9aeb-01f0639e7690,message:For connector ID: 871842996425:031cba04-ddc1-4077-bd73-5770e65efbd0:1d63b6af-eb0e-4f7c-8fd2-ddd12b163b86, current metric queue size is: 0 and previous queue size was: 13
2023-06-29 08:14:44.150  INFO 13304 --- [ol-1-worker-115] c.a.k.c.s.p.ServiceMessagePublisher      : logLevel:Info,caller:com.amazonaws.kendra.connector.sdk.core.crawler.DocumentCrawlerConnectorController.cleanUp()[Line:99],awsAccountId:871842996425,indexId:031cba04-ddc1-4077-bd73-5770e65efbd0,sourceId:1d63b6af-eb0e-4f7c-8fd2-ddd12b163b86,executionId:69899685-b89f-4a35-9aeb-01f0639e7690,message:Stopping custom DataSource sync.
2023-06-29 08:14:44.473  INFO 13304 --- [ol-1-worker-115] c.a.k.c.s.p.ServiceMessagePublisher      : logLevel:Info,caller:com.amazonaws.kendra.connector.sdk.core.crawler.DocumentCrawlerConnectorController.cleanUp()[Line:102],awsAccountId:871842996425,indexId:031cba04-ddc1-4077-bd73-5770e65efbd0,sourceId:1d63b6af-eb0e-4f7c-8fd2-ddd12b163b86,executionId:69899685-b89f-4a35-9aeb-01f0639e7690,message:Resetting and initializing the connector.
2023-06-29 08:14:44.473  INFO 13304 --- [ol-1-worker-115] c.a.k.c.s.p.ServiceMessagePublisher      : logLevel:Info,caller:com.amazonaws.kendra.connector.googledrive.client.GoogleDriveClient.resetAndInitialize()[Line:115],awsAccountId:871842996425,indexId:031cba04-ddc1-4077-bd73-5770e65efbd0,sourceId:1d63b6af-eb0e-4f7c-8fd2-ddd12b163b86,executionId:69899685-b89f-4a35-9aeb-01f0639e7690,message:Reset and initialization of connector.